### ISSUE TITLE
Alpha values not reflected correctly when loading colors added by `tailwindcss-themer` from other plugins

### ISSUE THREAD

**Issue by dungsil** [RyanClementsHax/tailwindcss-themer#121]
### Describe the bug

When the value applied to the themer is called into the theme function, the <alpha-value> is exposed as is (no color is applied).

![image](https://github.com/RyanClementsHax/tailwindcss-themer/assets/39783731/7a3b6a4e-7e64-4701-93f4-0eb5c2a2e19e)

### Your minimal, reproducible example

https://github.com/dungsil/issues/tree/main/tailwindcss-themer-121

### Steps to reproduce

1. define color values in themer plugin `backgroundColor`, `textColor`, `borderColor`, etc...
2. After adding the new plugin, use the values extended by `tailwindcss-themer`.
3. the alpha value will be output as `<alpha-value>` when applied.

### Expected behavior

It should output `1`, not `<alpha-value>`.

### How often does this bug happen?

Every time

### Platform

- OS: Windows 11 
- Browser: Firefox Devlopment Edition
- Node.js : v20.10.0

### tailwindcss-themer version

v4.0.0

**Comment by RyanClementsHax** [comment]
Thanks for opening this. I'll take a look at it soon

**Comment by RyanClementsHax** [comment]
It seems this is an existing bug/limitation within Tailwind. Looking at tailwind's open issues, it seems this should help https://github.com/tailwindlabs/tailwindcss/issues/9143#issuecomment-1684399533

This worked for me
```js
    plugin(function ({ addBase }) {
      addBase({
        '#plugin': {
          backgroundColor: "theme('backgroundColor.base')" // 👈🏻 Wrap it in a string instead
        }
      })
    })
```

Does this work for you?

I'm going to close this preemptively as expected behavior.
