### ISSUE TITLE
failed to load assets in subdomain app

### ISSUE THREAD

**Issue by SAliMotamedi** [RyanClementsHax/tailwindcss-themer#33]
### Describe the bug

hi
I have project that uploaded on subdomain url in server 
the problem is when I use multiple theme for admin and user panel  css file doesn't load in admin panel 
I don't know why but all the filament assets load correctly except css file 

### Your minimal, reproducible example

--

### Steps to reproduce

I dont know

### Expected behavior

I expected to load assets correctly

### How often does this bug happen?

Every time

### Screenshots or Videos

https://cdn.discordapp.com/attachments/883085267383226478/1009380663276884028/unknown.png 

### Platform

- os: nginx
- browser: chrome

### tailwindcss-themer version

2.0.1

**Comment by RyanClementsHax** [comment]
Hiya! Thanks for opening this issue.

Without a reproduction repo, I'm unable to help you with the problem.
