### ISSUE TITLE
fontFamily or another camel case attribute are creating kebab case variables

### ISSUE THREAD

**Issue by alanTechGC** [RyanClementsHax/tailwindcss-themer#38]
### Describe the bug

It's impossible to override any camel case attribute from tailwindcss.
The problem is when you translate the extend attributes to a variable.
For example 
```
{
fontFamily: {
    sans: ['monospace']
  }
}
```
It is translated to `--font-family-sans-0: Maison;`
But tailwind is using `--font-familySans-0: Maison;`

### Your minimal, reproducible example

-

### Steps to reproduce

Create any camel case attribute in a theme configuration and then inspect the element to see the value

### Expected behavior

I expect to get the variable in camel case

### How often does this bug happen?

Every time

### Platform

- OS Mac
- Browser Chrome

### tailwindcss-themer version

2.0.1

**Comment by RyanClementsHax** [comment]
Thanks for opening this issue!

Could you provide a reproduction example? I tried to replicate this locally, but couldn't. Below is my config

```js
//@ts-check

// this file is now type checked!!

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {}
  },
  plugins: [
    require('tailwindcss-themer')({
      defaultTheme: {
        extend: {
          colors: {
            primary: {
              // here I'm specifying a custom default
              500: 'blue'
            },
            secondary: {
              500: 'red'
            }
            // uncomment this and see that this causes a type error
            // thisCausesATypeError: () => '💥 boom! 💥'
          },
          fontFamily: {
            sans: ['monospace'] // tailwind uses --fontFamily-sans-0 for this
          }
        }
      },
      themes: [
        {
          name: 'dark',
          extend: {
            colors: {
              // here I'm overriding a custom default
              secondary: {
                500: 'darkred'
              },
              // here I'm overriding a custom default too
              primary: {
                500: 'darkblue'
              }
            }
          }
        },
        {
          name: 'neon',
          extend: {
            colors: {
              secondary: {
                // here I'm overwriting a custom default again
                500: '#90A040' // as red as it gets
              }
              // im not overwriting the custom primary color I made ... I wonder what will happen ??? 🤔🤔🤔
            }
          }
        }
      ]
    })
  ]
}
```

**Comment by RyanClementsHax** [comment]
Thanks for that. Could you provide an example config that reproduces this? I'm not sure what you mean.

**Comment by creaux** [comment]
```
//@ts-check

// this file is now type checked!!

module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {}
  },
  plugins: [
    require('tailwindcss-themer')({
      defaultTheme: {
        extend: {
          fontFamily: {
            sans: ['monospace']
          }
        }
      },
      themes: [
        {
          name: 'dark',
          extend: {
            fontFamily: {
              sans: ['Times'] // Times is not globally adopted when dark theme is used, even sans-serif is font used by default, instead monospace from "defaultTheme" is used
            }
          }
        },
      ]
    })
  ]
}
```

**Comment by RyanClementsHax** [comment]
I'm still having trouble reproducing what you're referring to. Here is an example repo with the config you listed, but everything is working as expected. https://codesandbox.io/p/devbox/polished-lake-6sntvm-6sntvm

Would you mind helping me out so I can see what issue y'all are facing?

**Comment by alanTechGC** [comment]
Sorry for the delay. This is my case:
I want to add a new font to a custom theme. So I added this:
```
themes: [
        {
          name: 'legal',
          extend: {
            fontFamily: {
              heading: ['Signifier'],
            },
          },
        },
      ]
```

This is what was generated in css:
<img width="1688" alt="image" src="https://github.com/RyanClementsHax/tailwindcss-themer/assets/113192599/60c7b61d-48b4-43ac-a246-077e9000d169">
![image](https://github.com/RyanClementsHax/tailwindcss-themer/assets/113192599/613667fc-9866-46fa-a5f1-8b3467166e1c)

And the workaround I mentioned is overriding that variable in my global css:
```
.cfo {
  --fontFamily-heading-0: Platform;
}
```
<img width="685" alt="image" src="https://github.com/RyanClementsHax/tailwindcss-themer/assets/113192599/102beedf-7623-4052-b202-730f3affc80d">

**Comment by RyanClementsHax** [comment]
Are you enabling your theme by adding the class `legal` to a parent?

**Comment by alanTechGC** [comment]
> Are you enabling your theme by adding the class `legal` to a parent?

Yes, of course
