### ISSUE TITLE
Idea for `defaultTheme` variant to exclude other themes, and some other thoughts

### ISSUE THREAD

**Issue by MichaelAllenWarner** [RyanClementsHax/tailwindcss-themer#5]
Something like `addVariant('defaultTheme', '&:not(.other-theme-1 *, .other-theme-2 *)')` might do the trick. Complex selectors in `:not()` have pretty good browser support at this point: https://caniuse.com/css-not-sel-list

In general, you might like to allow for a layer or two of "nesting" for the variants, so that, for example, the innermost div in the following would have a black background, regardless of the declaration-order in the CSS:

```html
<div class="theme-3">
  <div class="theme-2">
    <div class="theme-2:bg-black theme-3:bg-white"></div>
  </div>
</div>
```

Again, you can use a complex `:not()` selector:

```js
addVariant('theme-3', '.theme-3 &:not(.theme-3 .theme-1 *, .theme-3 .theme-2 *)')
```

To allow for more "nesting," maybe something like:

```js
addVariant('theme-3', `
  .theme-3 &:not(.theme-3 .theme-1 *, .theme-3 .theme-2 *),
  .theme-3 .theme-1 .theme-3 &,
  .theme-3 .theme-2 .theme-3 &
`)
```

(assuming `addVariant` even supports multiple selectors; if not, maybe a PostCSS plugin could do this). For `defaultTheme`, I guess you'd want something like:

```js
addVariant('defaultTheme', `
  &:not(.theme-1 *, .theme-2 *),
  .theme-1 .defaultTheme &,
  .theme-2 .defaultTheme &
`)
```

If the themes were indicated by attributes instead of classes, you might not have to list the other individual theme-names at all (though there's no "not-equals" attribute-selector, and you can't nest `:not()`s):

```js
addVariant('theme-3', `
  [data-tw-theme="3"] &:not([data-tw-theme="3"] [data-tw-theme] *),
  [data-tw-theme="3"] [data-tw-theme="3"] &
`)
```

Another layer of nesting might be possible but I doubt it would be useful.

This project seems really promising to me. I've been thinking along similar lines recently (as you can maybe tell).

One more unrelated idea (a little out there, admittedly): what if you could also make theme-_group_ variants, that apply selectors for several themes at once? For example, maybe your `theme-2`, `theme-3`, and `theme-4` all generally use white for the text-color—what if you could make a `themes-white-text` variant for all of them at once? Then `themes-white-text:text-decoration-white/50` could be shorthand for `theme-2:text-decoration-white/50 theme-3:text-decoration-white/50 theme-4:text-decoration-white/50`. Heck, maybe it would even be possible to use `matchUtilities` to allow for some JIT magic there, like `themes-[2,3,4|text-decoration-color-white/50]` (inspiration: https://play.tailwindcss.com/SLtXEpJPbJ).

**Comment by MichaelAllenWarner** [comment]
Hi @RyanClementsHax,

Thanks for the reply. Don't have a lot of time right now, but here is an attribute-driven approach that I've been fiddling with: https://play.tailwindcss.com/9ygk2ozUjG

**Comment by MichaelAllenWarner** [comment]
This updated version includes a JIT `matchUtilities` thing that seems to be working (for applying utilities to multiple themes using a "shorthand"): https://play.tailwindcss.com/4cchHMtasV

**Comment by MichaelAllenWarner** [comment]
@RyanClementsHax 

I think you and I might have meant different things by "exclude other themes": by itself, `addVariant('theme-default', '&:not(.theme-other-1 *, .theme-other-2 *)')` would just allow the `theme-default:` variant to be used anywhere except inside another theme's scope.

If by "exclude other themes" you meant "disable other theme-variants within this theme's scope," then that logic needs to be handled in the selectors for those other theme-variants, just as the `theme-default` logic above disables the `theme-default:` variant when an ancestor-element has established another theme's scope. For non-default themes, you'd be looking at something like:

```js
addVariant('theme-other-1', '.theme-other-1 &:not(.theme-default *, .theme-other-2 *)')
```

Here is a working demo with these selectors (class-based, and simpler than what I shared earlier): https://play.tailwindcss.com/OUCAeFK8Wy

(Theme-nesting requires more complex selectors.)

**Comment by RyanClementsHax** [comment]
Excellent work on creating that demo! I think that will be a useful reference when considering adding better support for nesting.

I think there was a bit of confusion between us. When talking about a `defaultTheme` variant. My goal is to only enable the class it is attached to if not in the scope of any other theme, not disabling any other theme (i.e. the class `defaultTheme` is attached to is disabled when in the scope of any active theme).

Thus, I'd like to leave other classes unaffected.

(Hope this helps)
