### ISSUE TITLE
theme classnames (and css custom properties) are not properly escaped

### ISSUE THREAD

**Issue by cloud-walker** [RyanClementsHax/tailwindcss-themer#64]
### Describe the bug

I want to override the default tailwind `spacing` variables, that supports values like `1.5` and `0.5`, but tailwind-themer does not escape them, like tailwind vanilla does.

### Your minimal, reproducible example

https://codesandbox.io/p/github/cloud-walker/repro-tw-themer/main?workspace=%257B%2522activeFilepath%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clgdw7o49000e3b6i6thrxuo6%2522%253A%257B%2522key%2522%253A%2522clgdw7o49000e3b6i6thrxuo6%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clgdw7zco006m3b6ijqmx14qy%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clgdw7xkn003f3b6i3twwmkgq%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clgdw7o49000e3b6i6thrxuo6%2522%252C%2522spacesOrder%2522%253A%255B%2522clgdw7o49000e3b6i6thrxuo6%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### Steps to reproduce

Just inspect the output

### Expected behavior

the classnames and css custom properties should be escaped, like tailwind does

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1144075/231519811-c38dce1c-0480-432a-a1e2-d6534a1a7625.png)

### Platform

- OS: MacOS
- Browser: Chrome latest

### tailwindcss-themer version

latest

**Comment by cloud-walker** [comment]
Think I've found the tailwind original code: https://github.com/tailwindlabs/tailwindcss/blob/fbbba6f67f73c3a4f9571649c3fc27006446d8f4/src/lib/regex.js#L70

**Comment by cloud-walker** [comment]
Found that the official plugin API expose an [encode](https://tailwindcss.com/docs/plugins#overview) function

**Comment by RyanClementsHax** [comment]
Thanks for opening the issue! I appreciate your patience. I had a bunch of crazy things happen in the last month and now I'm able to devote more time to OSS.

**Comment by RyanClementsHax** [comment]
Thanks for the research you've put into this and the reproduction example. That was very helpful and appreciated. I'd be happy to let you contribute. What do you need from me to get started?

**Comment by RyanClementsHax** [comment]
Oh! I see your PR now. I gave it a review
