### ISSUE TITLE
Idea for "theme-grouping" utility classes

### ISSUE THREAD

**Issue by MichaelAllenWarner** [RyanClementsHax/tailwindcss-themer#7]
With Tailwind's `matchUtilities` API, it's possible to use arbitrary-value syntax to apply utility classes to multiple themes in a single declaration, like:

```html
<div class="themes-[theme-1,theme-2|bg-black•underline]">...</div>
```

where I've chosen the `|` character to separate the theme-names from the utility classes, a comma to separate the theme-names from each other, and the bullet to separate the utility-classes from each other. Here is the `matchUtilities` plugin I've used to achieve this:

```js
matchUtilities({
  themes: value => {
    // pipe separates theme-names from utility-classes
    const [rawThemeNames, rawUtilities] = value.split('|');

    // commas separate theme-names, bullets separate utility-classes
    const themeNames = rawThemeNames.split(',');
    const utilities = rawUtilities.split('•');

    const themedUtilities = themeNames.flatMap(themeName => (
      utilities.map(utility => `theme-${themeName}:${utility}`)
    ));

    return {
      '&': {
        [`@apply ${themedUtilities.join(' ')}`]: '',
      },
    };
  },
});
```

Here is a working demo (this demo also includes the nesting-mechanism I mentioned in https://github.com/RyanClementsHax/tailwindcss-themer/issues/6): https://play.tailwindcss.com/gpeh0ciLbe

Worth noting that because of the `@apply`, Tailwind will give you an error message if you try to use an invalid utility-class.

**Comment by RyanClementsHax** [comment]
Great idea! I'm going to let this sit open for a bit so adoption can mature better.

The idea here is that I want to see how people use this plugin before we move forward.
